packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@firebase/util': true
  esbuild: true
  protobufjs: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@firebase/util'
  - esbuild
  - protobufjs
  - unrs-resolver
