# Build from the backend repository root:
#   docker build -f deploy/docker/Dockerfile.nginx -t c1rcle-nginx:local .

FROM nginx:1.27-alpine@sha256:65645c7bb6a0661892a8b03b89d0743208a18dd2f3f17a54ef4b76fb8e2f2a10

RUN rm -f /etc/nginx/conf.d/default.conf \
    && mkdir -p /etc/nginx/snippets/c1rcle /etc/nginx/c1rcle-templates

COPY deploy/nginx/nginx.conf /etc/nginx/nginx.conf
COPY deploy/nginx/snippets/ /etc/nginx/snippets/c1rcle/
COPY deploy/nginx/templates/staging.conf.template /etc/nginx/c1rcle-templates/staging.conf.template
COPY deploy/nginx/templates/production.conf.template /etc/nginx/c1rcle-templates/production.conf.template
COPY deploy/docker/nginx-entrypoint.sh /usr/local/bin/c1rcle-nginx-entrypoint

RUN chmod 0755 /usr/local/bin/c1rcle-nginx-entrypoint

ENTRYPOINT ["/usr/local/bin/c1rcle-nginx-entrypoint"]
